ALTER TABLE "MarketPrice" ADD COLUMN IF NOT EXISTS "updatedBy" TEXT;
ALTER TABLE "MarketPrice" ADD COLUMN IF NOT EXISTS "updatedByName" TEXT;
ALTER TABLE "MarketPrice" ADD COLUMN IF NOT EXISTS "history" TEXT;
