ALTER TABLE "ShipmentDetail" ADD COLUMN IF NOT EXISTS "royaltyCost" DOUBLE PRECISION;
ALTER TABLE "ShipmentDetail" ADD COLUMN IF NOT EXISTS "taxExportCost" DOUBLE PRECISION;
ALTER TABLE "ShipmentDetail" ADD COLUMN IF NOT EXISTS "surveyCost" DOUBLE PRECISION;
ALTER TABLE "ShipmentDetail" ADD COLUMN IF NOT EXISTS "paymentFinanceCost" DOUBLE PRECISION;

ALTER TABLE "PLForecast" ADD COLUMN IF NOT EXISTS "royaltyCost" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "PLForecast" ADD COLUMN IF NOT EXISTS "taxCost" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "PLForecast" ADD COLUMN IF NOT EXISTS "surveyCost" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "PLForecast" ADD COLUMN IF NOT EXISTS "paymentCost" DOUBLE PRECISION NOT NULL DEFAULT 0;
